import re

advanced_tokenizer_tags = {'aa':['a','a'],
                           'aam':['a','am'],
                           'ee':['i','i'],
                           'oo':['u','u'],
                           'e':['a','i'],
                           'o':['a','u'],
                           'ya':['i','a'],
                           'yaa':['i','aa'],
                           'yu':['i','u'],
                           'yoo':['i','oo'],
                           'ye':['i','e'],
                           'yo':['i','o'],
                           'va':['u','a'],
                           'vaa':['u','aa'],
                           'vu':['u','u'],
                           'voo':['u','oo'],
                           've':['u','e'],
                           'vo':['u','o'],
                           'vam':['u','am'],
                           'vi':['u','i'],
                           'vee':['u','ee'],
                           'vai':['u','ai'],
                           'vau':['u','au'],
                           'ai':['a','e'],
                           'au':['a','o'],
                           'ar':['a','ru'],

                           'ga':['k','a'],
                           'gaa':['k','aa'],
                           'gi':['k','i'],
                           'gee':['k','ee'],
                           'gu':['k','u'],
                           'goo':['k','oo'],
                           'ge':['k','e'],
                           'gai':['k','ai'],
                           'go':['k','o'],
                           'gau':['k','au'],
                           'gam':['k','am'],

                           'chcha':['t','cha'],
                           'jja':['t','ja'],
                           'nna':['t','na'],
                           'lla':['t','la'],

                           'da':['t','a'],
                           'daa':['t','aa'],
                           'du':['t','u'],
                           'dbh':['t','bh'],
                           'dg':['t','g'],
                           'dk':['t','k'],

                           'iSh':['i','s'],
                           'uSh':['u','s'],


                           }
